add render instructions, adjust documentation for cleaner config
GrahamCampbell/Laravel-Exceptions pull request #108
Opened 2017-05-08 14:51 UTC by mikeerickson

- [x] Updated `README.md` configuration instructions 
- [x] Updated `README.md` to add `render` changes as defined in https://github.com/GrahamCampbell/Laravel-Exceptions/issues/107 issue

2017-06-01 22:58 UTC, GrahamCampbell commented
Thanks for the PR. Going to sleep on this, then look at it again. :)

2017-06-09 12:53 UTC, aalyusuf commented
+1 for this

2017-06-13 02:54 UTC, mikeerickson commented
@GrahamCampbell must be hibernating 👍

2017-06-26 21:56 UTC, GrahamCampbell requested changes

2017-06-26 21:56 UTC, GrahamCampbell commented on README.md
> +####  Adjust Render Method
I actually would not recommend editing the render method.

2017-06-26 21:56 UTC, GrahamCampbell commented on README.md
> +####  Adjust Render Method
This should be handled by writing a displayer.

2017-06-26 21:58 UTC, GrahamCampbell commented on README.md
> +####  Adjust Render Method
I really don't like laravel's native exception handler, and the way Laravel deals with errors across the board, by just saying "is json wanted", when actually, the correct thing to say is, "what does the client prefer out of the content types that i can respond with".

2017-07-30 13:25 UTC, closed without merging