Update tests
GrahamCampbell/Laravel-Exceptions pull request #133
Opened 2019-03-05 19:59 UTC by Lavoaster

I did a sneaky and updated the config file to use the class syntax, but if you don't want that then that's fine, I'll be happy to remove it.

2019-03-05 20:05 UTC, GrahamCampbell commented
Please revert the changes to the config file.

2019-03-05 20:06 UTC, GrahamCampbell commented
Could you also import things in the tests, rather than a global escape. Thanks. If the tests pass after that, I'll merge. :)

2019-03-05 22:22 UTC, Lavoaster commented
Can you make style ci fail on that then please?

2019-03-05 22:35 UTC, Lavoaster commented
Not sure how I missed the imports, considering they're literally used two lines above, but thanks for catching that. I do import them in my own code. I was probably thrown of by the use of the global escape in the docblock.

Anyway, I have trashed the config change and squashed everything together. :)

2019-03-10 11:20 UTC, GrahamCampbell requested changes

2019-03-10 11:20 UTC, GrahamCampbell commented on tests/Displayers/DebugDisplayerTest.php
> +        $this->assertIsString($response->getContent());
This method does not exist in PHPUnit 6.5, which is why the tests are failing.

2019-03-10 11:23 UTC, merged

2019-03-10 11:24 UTC, GrahamCampbell commented
Thanks @Lavoaster. :)